const RestaurantData = [
    { name: "Rashbhare Gulabjamun", type: "Sweets and Namkeen", rating: 4.4, deliveryTime: 38, imageSrc: "gulab_jamun.avif" },
    { name: "Cold Cofffe", type: "foods", rating: 4.6, delliveryTime:29, imageSrc:"coldcoffe.avif"},
    { name: "Rolls", type: "Mexican", rating: 3.9, deliveryTime: 38.28, imageSrc: "Taco.avif" },
    { name: "Ice Cream", type: "Desserts,Ice Cream", rating: 4.1, delliveryTime:50.10, imageSrc:"Baskin Robbins.avif"},
    { name: "Haldiram's Special", type: "Chinese, North Indian ", rating: 4.0, deliveryTime: 38.40, imageSrc: "Haldiram's Restaurant.avif" },
    { name: "All Rolls", type: "Roll & Roll", rating: 4.4, deliveryTime: 38, imageSrc: "Rolls.webp" },
    { name: "Subway Special", type: "Healthy foods", rating: 4.6, delliveryTime:30 , imageSrc:"Subway.avif"},
    { name: "Rajhans Thali ", type: "Thalis, Indian sarafa", rating: 4.6, deliveryTime: 38, imageSrc: "Hotel Rajhans.avif" },
    { name: "Cakes", type: "Cakes", rating: 4.0, delliveryTime:25, imageSrc:"cakes.avif"},
    { name: "KFC ", type: "Non veg", rating: 4.7, deliveryTime: 38, imageSrc: "KFC.avif" },
    { name: "McDonald's", type: "Fast Foods", rating: 4.8, delliveryTime:39, imageSrc:"MCd.avif"},
    { name: "North Indian Thali", type: "Dal Chawal", rating: 4.9, deliveryTime: 38, imageSrc: "dal chawal.avif"},
    { name: "Cold Coffe", type: "coldcoffe", rating: 4.4, deliveryTime: 38, imageSrc: "starbucks coffe.avif" },
    { name: "Cakes", type: "Cakes", rating: 4.0, delliveryTime:25, imageSrc:"cakes.avif"},
    { name: "Dal Chawal Thali", type: "Dal Chawal", rating: 4.9, deliveryTime: 38, imageSrc: "dal chawal.avif"},
    { name: "All Rolls", type: "Roll & Roll", rating: 4.4, deliveryTime: 38, imageSrc: "Rolls.webp" },
    { name: "All Rolls", type: "Roll & Roll", rating: 4.4, deliveryTime: 38, imageSrc: "Rolls.webp" },
    { name: "Cheede burger", type: "Healthy foods", rating: 4.6, delliveryTime:30 , imageSrc:"Subway.avif"},
    { name: "Dal Bati", type: "Thalis, Indian sarafa", rating: 4.6, deliveryTime: 38, imageSrc: "Hotel Rajhans.avif" },
    { name: "Summer Special", type: "Ice - Cream", rating: 4.6, delliveryTime:29, imageSrc:"Kwality.avif"},
    { name: "Non veg", type: "Non veg", rating: 4.7, deliveryTime: 38, imageSrc: "KFC.avif" },
    { name: "McDonald's", type: "Fast Foods", rating: 4.8, delliveryTime:39, imageSrc:"MCd.avif"},
    { name: "North Indian Thali", type: "Dal Chawal", rating: 4.9, deliveryTime: 38, imageSrc: "dal chawal.avif"},
    { name: "StarBucks ", type: "coldcoffe", rating: 4.4, deliveryTime: 38, imageSrc: "starbucks coffe.avif" },
    { name: "Cakes & Crafts", type: "Cakes", rating: 4.0, delliveryTime:25, imageSrc:"cakes.avif"},
    { name: "All Rolls", type: "Roll & Roll", rating: 4.4, deliveryTime: 38, imageSrc: "Rolls.webp" },

];

export default RestaurantData;
